Feat/contact page
Datadvisor/frontend pull request #3
Opened 2022-05-03 09:29 UTC by Rgascoin

# Description
Add Contact Page and cypress setup + contact's page test

# Changes include
[ ] New feature (non-breaking change that adds functionality)
[ ] Bugfix (non-breaking change that solves an issue)
[x] Breaking change (change that is not backwards-compatible and/or changes current functionality)
# Checklist
...

2022-05-05 22:21 UTC, MrZalTy requested changes

2022-05-05 22:21 UTC, MrZalTy commented on cypress/integration/Contact/contact_form.spec.js
> +    cy.contains('Le prénom ne peux être vide')
Fix misspelling

2022-05-05 22:21 UTC, MrZalTy commented on package-lock.json
> +{
Remove this file

2022-05-05 22:31 UTC, MrZalTy requested changes

2022-05-05 22:31 UTC, MrZalTy commented on package.json
> +    "cypress": "^9.6.0",
cypress, @tailwindcss/forms, @tailwindcss/aspect-ratio should be in devDependencies.

2022-05-16 21:32 UTC, Rgascoin commented on package.json
> +    "cypress": "^9.6.0",
Fixed in [0bf8ee0](https://github.com/Datadvisor/frontend/pull/3/commits/0bf8ee0eec754cc288091916fbef0178ccf5ccb2)

2022-05-16 21:32 UTC, Rgascoin commented on package-lock.json
> +{
Fixed in [992bcb1](https://github.com/Datadvisor/frontend/pull/3/commits/992bcb145015d28d7d7e5adc7c7e4a8f293431e8)

2022-05-16 21:32 UTC, Rgascoin commented on cypress/integration/Contact/contact_form.spec.js
> +    cy.contains('Le prénom ne peux être vide')
Fixed in [d88c4b2](https://github.com/Datadvisor/frontend/pull/3/commits/d88c4b250dd8ac626e24bac6b84e487b33e01db6)

2022-05-17 19:37 UTC, MrZalTy approved these changes
OK

2022-05-17 19:38 UTC, merged